//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chromatik {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceChromatik {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceChromatik() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chromatik.ResourceChromatik", typeof(ResourceChromatik).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;XML&gt;
        ///  &lt;Charsets&gt;
        ///    
        ///    &lt;Charset nameID=&quot;ASCII&quot;&gt;
        ///      &lt;Name lang=&quot;en&quot;&gt;ASCII&lt;/Name&gt;
        ///      &lt;Description lang=&quot;en&quot;&gt;&lt;/Description&gt;
        ///      &lt;Localisable&gt;
        ///        &lt;Languages lang=&quot;en&quot;&gt;&lt;/Languages&gt;
        ///        &lt;Countries lang=&quot;en&quot;&gt;&lt;/Countries&gt;
        ///      &lt;/Localisable&gt;
        ///      &lt;CodeRange&gt;
        ///        &lt;Range&gt;0000-007F&lt;/Range&gt;
        ///      &lt;/CodeRange&gt;
        ///    &lt;/Charset&gt;
        ///    &lt;Charset nameID=&quot;Latin-1&quot;&gt;
        ///      &lt;Name lang=&quot;en&quot;&gt;Latin-1&lt;/Name&gt;
        ///      &lt;Description lang=&quot;en&quot;&gt;Latin-1 Western E [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Charsets_XML {
            get {
                return ResourceManager.GetString("Charsets_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;XML&gt;
        ///  &lt;Unicode&gt;
        ///    
        ///    &lt;Plane nameID=&quot;Basic Multilingual Plane&quot;&gt;
        ///      &lt;Name lang=&quot;en&quot;&gt;Basic Multilingual Plane&lt;/Name&gt;
        ///      &lt;Name lang=&quot;fr&quot;&gt;Plan multilingue de base&lt;/Name&gt;
        ///      &lt;Description lang=&quot;en&quot;&gt;&lt;/Description&gt;
        ///      &lt;Block nameID=&quot;C0 Controls&quot;&gt;
        ///        &lt;Name lang=&quot;en&quot;&gt;C0 Controls&lt;/Name&gt;
        ///        &lt;Name lang=&quot;fr&quot;&gt;Controle C0&lt;/Name&gt;
        ///        &lt;Description lang=&quot;en&quot;&gt;&lt;/Description&gt;
        ///        &lt;Localisable&gt;
        ///          &lt;Languages&gt;&lt;/Languages&gt;
        ///          &lt;Coun [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Unicode_XML {
            get {
                return ResourceManager.GetString("Unicode_XML", resourceCulture);
            }
        }
    }
}
