//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chromatik {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chromatik.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;!--
        ///    This HTML DTD is based on loose.dtd from the W3C, but it is even looser
        ///    so as to allow for the types of real world messy HTML you find out on the
        ///    web.  For example, allowing all kinds of content like &lt;script&gt; inside a &lt;TD&gt;
        ///    and so forth.
        ///--&gt;
        ///&lt;!ENTITY % HTML.Version &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot;
        ///  -- Typical usage:
        ///
        ///    &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot;
        ///            &quot;http://www.w3.org/TR/html4/loose.dtd&quot;&gt;
        ///    &lt;html&gt;
        ///    &lt;head&gt;
        ///    ...
        ///  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Html_dtd {
            get {
                return ResourceManager.GetString("Html_dtd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à public static class {0} {
        ///static internal Regex _regex = new Regex(&quot;{1}&quot;, ({2}), new TimeSpan({3}));
        ///static public string Pattern { get { return _regex.ToString(); } }
        ///static public RegexOptions Options { get { return _regex.Options; } }
        ///static public TimeSpan MatchTimeout { get { return _regex.MatchTimeout; } }
        ///static public bool RightToLeft { get { return _regex.RightToLeft; } }
        ///static public string[] GetGroupNames() { return _regex.GetGroupNames(); }
        ///static public int[] GetGroupNumbers() { return _ [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string RegexStatic {
            get {
                return ResourceManager.GetString("RegexStatic", resourceCulture);
            }
        }
    }
}
